// Generated bridge for IRIS - flutter_rust_bridge bindings.
// Maps to iris_flutter/rust/src/api/iris_api.rs
//
// This file is normally generated by `flutter_rust_bridge_codegen`.
// For manual integration, we provide the FFI bindings directly.

import 'dart:ffi';
import 'dart:io';
import 'package:ffi/ffi.dart';
import 'package:flutter/foundation.dart';

// ── Library Loading ────────────────────────────────────────────────

DynamicLibrary _loadLib() {
  if (Platform.isAndroid) {
    return DynamicLibrary.open('libiris_bridge.so');
  } else if (Platform.isLinux) {
    return DynamicLibrary.open('libiris_bridge.so');
  } else if (Platform.isMacOS) {
    return _loadMacOsLib();
  } else if (Platform.isWindows) {
    return DynamicLibrary.open('iris_bridge.dll');
  } else {
    throw UnsupportedError('Unsupported platform: ${Platform.operatingSystem}');
  }
}

DynamicLibrary _loadMacOsLib() {
  // Try multiple paths to find the dylib
  final executableDir = Directory(Platform.resolvedExecutable).parent.path;

  final paths = [
    // Bundled in .app/Frameworks (production)
    '$executableDir/../Frameworks/libiris_bridge.dylib',
    // Same directory as executable (development)
    '$executableDir/libiris_bridge.dylib',
    // Project native/ directory (development, fallback)
    '${Directory.current.path}/native/libiris_bridge.dylib',
  ];

  for (final path in paths) {
    if (File(path).existsSync()) {
      debugPrint('[IRIS] Loading bridge library from: $path');
      return DynamicLibrary.open(path);
    }
  }

  throw Exception(
    'Cannot find libiris_bridge.dylib. Tried:\n${paths.join('\n')}\n'
    'Run ./build.sh first.',
  );
}

final _lib = _loadLib();

// ── FFI Type Definitions ───────────────────────────────────────────

typedef _StringFnNative = Pointer<Utf8> Function();
typedef _StringFnDart = Pointer<Utf8> Function();

typedef _StringStringFnNative = Pointer<Utf8> Function(Pointer<Utf8>);
typedef _StringStringFnDart = Pointer<Utf8> Function(Pointer<Utf8>);

typedef _FreeStringNative = Void Function(Pointer<Utf8>);
typedef _FreeStringDart = void Function(Pointer<Utf8>);

// Wire functions - flutter_rust_bridge uses "wire_" prefix
final _wireIrisInit = _lib.lookupFunction<
    Pointer<Utf8> Function(Pointer<Utf8>, Pointer<Utf8>, Pointer<Utf8>),
    Pointer<Utf8> Function(Pointer<Utf8>, Pointer<Utf8>, Pointer<Utf8>)>('wire_iris_init');

final _wireIrisStart = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_start');

final _wireIrisRestartWithPort = _lib.lookupFunction<
    Pointer<Utf8> Function(Uint16),
    Pointer<Utf8> Function(int)>('wire_iris_restart_with_port');

final _wireIrisGetDevices = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_get_devices');

final _wireIrisConnect = _lib.lookupFunction<_StringStringFnNative, _StringStringFnDart>(
    'wire_iris_connect');

final _wireIrisCaptureFrame = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_capture_frame');

final _wireIrisEncodeFrame = _lib.lookupFunction<
    Pointer<Utf8> Function(Pointer<Uint8>, Uint32, Uint32, Uint32, Uint8),
    Pointer<Utf8> Function(Pointer<Uint8>, int, int, int, int)>('wire_iris_encode_frame');

final _wireIrisDecodeFrame = _lib.lookupFunction<
    Pointer<Utf8> Function(Pointer<Utf8>, Uint32, Uint32, Uint8),
    Pointer<Utf8> Function(Pointer<Utf8>, int, int, int)>('wire_iris_decode_frame');

final _wireIrisGetVersion = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_get_version');

final _wireIrisListFiles = _lib.lookupFunction<_StringStringFnNative, _StringStringFnDart>(
    'wire_iris_list_files');

final _wireIrisDisplayDimensions = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_display_dimensions');

final _wireIrisUdpSend = _lib.lookupFunction<
    Pointer<Utf8> Function(Pointer<Utf8>, Pointer<Utf8>),
    Pointer<Utf8> Function(Pointer<Utf8>, Pointer<Utf8>)>('wire_iris_udp_send');

final _wireIrisUdpReceiveLatest = _lib.lookupFunction<_StringFnNative, _StringFnDart>(
    'wire_iris_udp_receive_latest');

final _freeString = _lib.lookupFunction<_FreeStringNative, _FreeStringDart>(
    'iris_free_string');

// ── Helper ─────────────────────────────────────────────────────────

String _callStr(Pointer<Utf8> ptr) {
  final result = ptr.toDartString();
  _freeString(ptr);
  return result;
}

Pointer<Utf8> _toUtf8(String s) => s.toNativeUtf8();

// ── Public API ─────────────────────────────────────────────────────

/// Initialize the IRIS engine.
String irisInit({
  required String deviceName,
  required String platform,
  required String downloadDir,
}) {
  final nName = _toUtf8(deviceName);
  final nPlatform = _toUtf8(platform);
  final nDir = _toUtf8(downloadDir);
  final ptr = _wireIrisInit(nName, nPlatform, nDir);
  calloc.free(nName);
  calloc.free(nPlatform);
  calloc.free(nDir);
  return _callStr(ptr);
}

/// Start discovery + transport services.
String irisStart() => _callStr(_wireIrisStart());

/// Restart with a specific TCP port (UDP = TCP + 1).
String irisRestartWithPort(int tcpPort) =>
    _callStr(_wireIrisRestartWithPort(tcpPort));

/// Get discovered devices as JSON.
String irisGetDevices() => _callStr(_wireIrisGetDevices());

/// Connect to a remote device.
String irisConnect({required String address}) {
  final nAddr = _toUtf8(address);
  final ptr = _wireIrisConnect(nAddr);
  calloc.free(nAddr);
  return _callStr(ptr);
}

/// Capture a frame from primary display.
String irisCaptureFrame() => _callStr(_wireIrisCaptureFrame());

/// Encode raw RGBA frame for UDP transmission.
String irisEncodeFrame({
  required List<int> rgbaData,
  required int width,
  required int height,
  required int encodingType,
}) {
  final data = calloc<Uint8>(rgbaData.length);
  for (var i = 0; i < rgbaData.length; i++) {
    data[i] = rgbaData[i];
  }
  final ptr = _wireIrisEncodeFrame(data, rgbaData.length, width, height, encodingType);
  calloc.free(data);
  return _callStr(ptr);
}

/// Decode received frame data.
String irisDecodeFrame({
  required String base64Data,
  required int width,
  required int height,
  required int encodingType,
}) {
  final nData = _toUtf8(base64Data);
  final ptr = _wireIrisDecodeFrame(nData, width, height, encodingType);
  calloc.free(nData);
  return _callStr(ptr);
}

/// Get protocol version info.
String irisGetVersion() => _callStr(_wireIrisGetVersion());

/// List shareable files.
String irisListFiles({required String dirPath}) {
  final nPath = _toUtf8(dirPath);
  final ptr = _wireIrisListFiles(nPath);
  calloc.free(nPath);
  return _callStr(ptr);
}

/// Get display dimensions.
String irisDisplayDimensions() => _callStr(_wireIrisDisplayDimensions());

/// Send encoded frame via UDP to a target address.
String irisUdpSend(String target, String encodedB64) {
  final nTarget = _toUtf8(target);
  final nData = _toUtf8(encodedB64);
  final ptr = _wireIrisUdpSend(nTarget, nData);
  calloc.free(nTarget);
  calloc.free(nData);
  return _callStr(ptr);
}

/// Get the latest received UDP frame.
String irisUdpReceiveLatest() => _callStr(_wireIrisUdpReceiveLatest());
